.gitignore, api/serializers.py, api/tests.py, api/views/posts_views.py
[#9] 에서 제가 한다고 했던 QuestionPost관련 view두개를 구현했어요
테스트도 짜서 돌렸어요
=> [Backend] Impelement QuestionPost views [Issue #9]

api/models.py, api/tests.py, api/views/auth_views.py, api/views/posts_views.py, utils/response.py
#11에서 작성한 대로 response 포맷을 통일했어요.
일일이 값을 작성하기 번거로울 것 같아 wrapper function을 작성했습니다.
* 기존 방식
```python
return Response(data, status=status)
```
* using wrapper
```python
from utils.response import generate_response
return generate_response(data, status=status)
return generate_response(data, message='message', status=status)
return generate_response(message='message', status=status)
```
=> [#11] Response format 통일

api/tests.py, api/views/list_views.py, api/views/posts_views.py
Implement information views mentioned in Issue #14 . 
Also implemented list views mentioned in Issue #17 .
Basic tests are also done.
Note that most of the codes are similar with question view.
=> Implement  views mentioned in Issue #14 and #17

api/serializers.py, api/tests.py, api/urls.py, api/views/auth_views.py, backend/settings.py
인증 방식을 basic authentication 에서 session authentication으로 바꿨어요.
그리고 확인 차 userinfo API를 활성화하고 약간 수정했습니다.
아직 테스트 코드가 완성 안되어 있어서 커버리지가 떨어질텐데, userinfo API가 없으면 프론트에서 에러가 날 거라 프론트 구현할 사람을 위해서 PR을 날려둡니다. 곧 테스트 추가할게요.
=> Changed authentication method

api/tests.py, api/views/posts_views.py
Implement question & information DELETE mentioned in #22.
Basic tests are also done
=> Implement question & information DELETE mentioned in #22.

api/tests.py, api/views/posts_views.py
Fix error in writing question view ( [POST] /api/question )
=> Fix error in writing question view ( [POST] /api/question )

api/serializers.py, api/tests.py, api/views/posts_views.py
From now, POST methods returns posted data after successful post.
=> From now, POST methods returns posted data after successful post.

api/tests.py, api/urls.py, api/views/auth_views.py, api/views/posts_views.py
=> [#28] Add signout API

api/views/auth_views.py
Fix error in swagger decorator.
Blame @ryanking13
=> Fix error in swagger decorator.

api/tests.py, api/views/posts_views.py
[#38] Change 204 status codes to 200, according to issue.
🤔
=> [#38] Change 204 status codes to 200, according to issue.

backend/settings.py
Time zone을 UTC에서 Asia/Seoul로 수정했습니다.
=> Change time zone

api/tests.py, api/views/posts_views.py
Issue #43. Add authorization to post views.
=> Issue #43. Add authorization to post views.

api/models.py, api/test_questionpost_view.py, api/views/list_views.py, api/views/posts_views.py
Resolve issue #42, #44. Implement some minor features.
=>  Resolve issue #42, #44. Implement some minor features.

api/test_questionpost_view.py, api/views/posts_views.py
=> Implement answer POST and GET

api/views/list_views.py, api/views/posts_views.py, utils/response.py
=> Fix issue #54.

api/models.py, api/views/list_views.py
Fix issue #56 and InformationPost model
=>  Fix issue #56 and InformationPost model

api/views/posts_views.py
Fix response data of informationpost view.
=> Fix response data of informationpost view.

api/models.py, api/serializers.py, api/test_informationpost_view.py, api/test_list_view.py, api/urls.py, api/views/list_views.py
Implement some features related with tags.
Implement Issue #50 
Fix Issue #59
=> Implement some features related with tags.

api/views/list_views.py
Fix issue #61. Now list api return objects with valid due.
=> Fix issue #61. Now list api return objects with valid due.

api/test_informationpost_view.py, api/test_questionpost_view.py, api/views/posts_views.py
=> Modify PATCH to PUT

api/views/posts_views.py
=> Fix issue #69

api/serializers.py
Fix QuestionAnswer serializer. Now response contains answer id.
=> Fix QuestionAnswer serializer. Now response contains answer id.

api/test_informationpost_view.py, api/views/posts_views.py
Fix issue #73
Now sponsorcredit is deducted from profile credit.
=> Fix issue #73

api/views/posts_views.py
=> Implement credit payments.

api/urls.py, api/views/information_views.py, api/views/question_views.py
Refactor some codes for further implementation.
=> Refactor some codes for further implementation.

api/test_notification_view.py, api/urls.py, api/views/debug_views.py, api/views/notification_views.py
Implement newsfeed and fix issue #86
=> Implement newsfeed and fix issue #86

api/views/auth_views.py
=> Fix bug in signin.

api/models.py, api/serializers.py, api/test_notification_view.py, api/urls.py, api/views/information_views.py, api/views/notification_views.py, api/views/question_views.py
#92 Implement favorite tags and notifications.
=> #92 Implement favorite tags and notifications.

api/views/information_views.py, api/views/question_views.py
Fix notification type message.
=> Fix notification type message.

api/models.py, api/serializers.py, api/test_informationpost_view.py, api/views/vote_views.py
Add vote system on backend #93
=> Add vote system on backend #93

api/test_list_view.py, api/views/auth_views.py, api/views/information_views.py, api/views/list_views.py, api/views/notification_views.py, api/views/vote_views.py
Fix information list ordering. Issue #101
=> Fix information list ordering. Issue #101

api/views/list_views.py
Fix information ordering issue
=> Fix information ordering issue
